### ISSUE TITLE
import Error !

### ISSUE THREAD

**Issue by CHB-learner** [orweis/winpcapy#22]
# from winpcapy import WinPcapUtils

 ImportError: cannot import name 'Callable' from 'collections'

**Comment by orweis** [comment]
Please see https://github.com/orweis/winpcapy/issues/21

**Comment by woistdiekatze** [comment]
Hi, could you please release this fix to pypi? Best regards

**Comment by orweis** [comment]
> Hi, could you please release this fix to pypi? Best regards

Done as - winpcapy 1.0.3
Note (I'm on Mac now 😅 ) - so made this just as a source-distribution

**Comment by woistdiekatze** [comment]
Thank's a lot!
