### ISSUE TITLE
after pip install i get a error

### ISSUE THREAD

**Issue by LiuYanming6** [orweis/winpcapy#7]
C:\Users\liu>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpcapy import WinPcapUtils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\liu\AppData\Local\Programs\Python\Python35-32\lib\site-packages\winpcapy\__init__.py", line 12, in <module>
    from winpcapy import WinPcap, WinPcapDevices, WinPcapUtils
ImportError: cannot import name 'WinPcap'
>>>

**Comment by orweis** [comment]
Right you are (A Python 3 issue).
I've already committed a fix here (making the import within __init__.py relative)
Will update the package at PyPi later today so you can fix with pip --upgrade (Will let you know once I do).
Meanwhile you can look at the recent commit if you want to apply the fix yourself.

**Comment by orweis** [comment]
Uploaded to PyPi.
Upgrade by running "pip install winpcapy --upgrade"
